/*
 * This file is generated by jOOQ.
*/
package com.fna.learning.db;


import com.fna.learning.db.tables.Country;
import com.fna.learning.db.tables.Databasechangelog;
import com.fna.learning.db.tables.Databasechangeloglock;
import com.fna.learning.db.tables.Department;
import com.fna.learning.db.tables.Employee;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Messaging extends SchemaImpl {

    private static final long serialVersionUID = 834605314;

    /**
     * The reference instance of <code>messaging</code>
     */
    public static final Messaging MESSAGING = new Messaging();

    /**
     * The table <code>messaging.country</code>.
     */
    public final Country COUNTRY = com.fna.learning.db.tables.Country.COUNTRY;

    /**
     * The table <code>messaging.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = com.fna.learning.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>messaging.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = com.fna.learning.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>messaging.department</code>.
     */
    public final Department DEPARTMENT = com.fna.learning.db.tables.Department.DEPARTMENT;

    /**
     * The table <code>messaging.employee</code>.
     */
    public final Employee EMPLOYEE = com.fna.learning.db.tables.Employee.EMPLOYEE;

    /**
     * No further instances allowed
     */
    private Messaging() {
        super("messaging", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Country.COUNTRY,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Department.DEPARTMENT,
            Employee.EMPLOYEE);
    }
}
