/*
 * This file is generated by jOOQ.
*/
package com.fna.learning.db;


import com.fna.learning.db.tables.Country;
import com.fna.learning.db.tables.Databasechangelog;
import com.fna.learning.db.tables.Databasechangeloglock;
import com.fna.learning.db.tables.Department;
import com.fna.learning.db.tables.Employee;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in messaging
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>messaging.country</code>.
     */
    public static final Country COUNTRY = com.fna.learning.db.tables.Country.COUNTRY;

    /**
     * The table <code>messaging.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = com.fna.learning.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>messaging.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = com.fna.learning.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>messaging.department</code>.
     */
    public static final Department DEPARTMENT = com.fna.learning.db.tables.Department.DEPARTMENT;

    /**
     * The table <code>messaging.employee</code>.
     */
    public static final Employee EMPLOYEE = com.fna.learning.db.tables.Employee.EMPLOYEE;
}
